### ISSUE TITLE
The Data Editor has developed some inconvenient quirks

### ISSUE THREAD

**Issue by M4uler** [BattleScribe/Release#14]
Some changes have crept into the Data Editor a version or two before v2.01.13, mostly to do with navigating around the client using the keyboard but selecting categories for Root Selection Entries is affected also.

1) When clicking on categories for RSEs the focus springs to the top of the list after each tick/untick, making the user scroll back down the list each time to continue working.

2) When creating a Link using TAB to step through the elements of the UI, the focus/selection vanishes between "Link Type" and "(select)", forcing the use of a mouse to click on the Select drop-down and complete linking.

3) When creating new objects, the focus no longer defaults to the "Name" field, requiring a few TABs to get the focus right.

The last one is more of a nit-pick but the first two, after a few years of creating & maintaining CATs, really mess up my flow of work when quickly getting stuff done with just the keyboard. Were any of these quirks intentional?

**Comment by morvael** [comment]
On the other hand focus stealing by name field prevented easy operations on the tree using ctrl c and ctrl v.

https://github.com/BattleScribe/Release/issues/5

**Comment by Jonskichov** [comment]
Fixed in 2.01.14.107

Tabbing through the link panel does work, but there's not really any visual indicator that a field has focus (at least on Windows). Not sure if I can do anything about that. Instead, every text field in the edit pane will autoselect it's text when it gains focus. Should make it easier to see and allow easier copy/pasting.

@morvael Is right, I knew there was a reason I disabled auto-selecting the name field. It's because it messed up keyboard navigation of the tree and copy/paste keyboard shortcuts. I have implemented a workaround: hitting tab when a tree node is selected will send focus to the name field. So it's not auto-selecting the name field, but instead you can just hit tab once. I think this is a good compromise.

**Comment by amis92** [comment]
@Jonskichov will there be also a keyboard navigation shortcut to go *back* to tree view? I'd propose `Esc`.

**Comment by Jonskichov** [comment]
@amis92 Sounds sensible. I think shift-tab is the default "previous focus" shortcut, does that work?

**Comment by amis92** [comment]
It could, but then it'd only work from the first field, I guess, as from every next, it'd just go back to the previous field?
