### ISSUE TITLE
Links **STILL** not validating

### ISSUE THREAD

**Issue by alphalas** [BattleScribe/Release#163]
https://github.com/BSData/wh40k/issues/6945

<img width="1188" alt="Screen Shot 2020-04-23 at 18 23 34" src="https://user-images.githubusercontent.com/15703066/80155395-a4cdf500-858f-11ea-82e1-f1a04dbfac62.png">

**Comment by Jonskichov** [comment]
I'm not sure how to reproduce the problem.

Can you give me a step-by-step please?

**Comment by alphalas** [comment]
Ok so if you make a character warlord, but do not give him a warlord trait, you should be able to assign a single tank an Ace Trait.

If you take the Tank Ace Stratagem, You should be able to assign a single tank an Ace Trait.

If you meet both conditions, you can have 2 single tanks with Ace Traits. 

As per the linked bugrep, it doesn’t work on the current builds

**Comment by Jonskichov** [comment]
This was fixed in the previous releases on all platforms:
- Android: 2.03.21
- iOS: 2.03.13
- Desktop: 2.03.15

Note that in the data that's currently in the repo, the "max 0 in roster" constraint doesn't have the "and child selections" or "and child forces" checkboxes checked, so it wasn't working. I had to fix that manually.

Also the in the BSData issue you linked failed to provide a version number so perhaps they just need to update :)

Added Leman Russ, added Tank Ace -> Error
Added Commander, added Warlord -> Error goes away
Added 2nd Leman Russ, added Tank Ace -> Error
Added Tank Ace strategem -> Error goes away
